name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore **/*.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore **/*.csproj
    - name: Pack CI Prerelease Version
      run: dotnet pack --configuration Release --no-restore --version-suffix "ci${{ github.run_number }}" 
      if: ${{ success() && !startsWith(github.ref, 'refs/tags/v') }}
    - name: Pack Tagged Version
      run: dotnet pack --configuration Release --no-restore -p:Version=$(echo ${{ github.ref }} | sed 's/.*\/v//')
      if: ${{ success() && startsWith(github.ref, 'refs/tags/v') }}
    - name: Upload Nuget package artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nuget-packages
        path: '**/*.nupkg'
