name: .NET

on:
  push:
    branches: [ master ]
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]
  pull_request:
    branches: [ master ]

jobs:
  buildandpublish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        DOTNET_NOLOGO: true

    - name: Variables

    - name: Restore dependencies
      run: dotnet restore **/*.csproj

    - name: Build
      run: dotnet build --configuration Release --no-restore **/*.csproj

    - name: Pack CI Prerelease Version
      shell: bash
      if: ${{ success() && !startsWith(github.ref, 'refs/tags/v') }}
      run: |
        dotnet pack \
          --configuration Release \
          --no-restore \
          --version-suffix "ci${{ github.run_number }}+${{ github.sha }}" \
          **/*.csproj


    - name: Pack Tagged Version
      if: ${{ success() && startsWith(github.ref, 'refs/tags/v') }}
      run: |
        dotnet pack \
          --configuration Release \
          --no-restore \
          -p:Version="$(echo ${{ github.ref }} | sed 's/.*\/v//')+${{ github.sha }}" \
          **/*.csproj

    - name: Nuget Push
      run: dotnet nuget push "**/*.nupkg" --skip-duplicate
